import assert from 'node:assert/strict';
import test from 'node:test';
import { db as realDb } from '@/lib/db';
import {
  approveStoryArchitectureApplyAction, buildArchitectureApplySourceSnapshot, buildArchitecturePlotPayload,
  cancelStoryArchitectureApplyAction, createStoryArchitectureApplyDraft, executeStoryArchitectureApplyAction,
  fingerprintArchitectureApplySnapshot, previewStoryArchitectureApplyAction, StoryArchitectureApplyError,
} from './apply-safety.js';
import { parseApplyActionRequest, parseApplyDraftRequest } from './apply-request.js';

type Row=Record<string,unknown>;
const now=()=>new Date('2026-10-06T00:00:00.000Z');
function source(overrides:Row={}):Row{return {id:'thread-1',architectureId:'architecture-1',status:'approved',provenance:'author',revision:2,proposalRunId:null,proposalAlternative:null,proposalRun:null,title:'静かな帰路',description:'二人が言葉を交わさず帰る。',threadType:'theme',customTypeLabel:null,createdAt:now(),updatedAt:now(),...overrides};}
function fakeDatabase(initialSource:Row=source(),options:{failPlot?:boolean}={}){
  let currentSource=initialSource;const plots:Row[]=[];const actions:Row[]=[];let sequence=0;
  const matchesStatus=(row:Row,where:Row)=>{const expected=where.status;if(typeof expected==='string')return row.status===expected;if(expected&&typeof expected==='object'&&Array.isArray((expected as Row).in))return ((expected as Row).in as unknown[]).includes(row.status);return true;};
  const applyDelegate={
    create:async({data}:{data:Row})=>{const row={id:`action-${++sequence}`,createdAt:now(),updatedAt:now(),approvedAt:null,appliedAt:null,failedAt:null,resultTargetId:null,errorCode:null,...data};actions.push(row);return row;},
    findFirst:async({where}:{where:Row})=>actions.find(row=>(where.id===undefined||row.id===where.id)&&(where.projectId===undefined||row.projectId===where.projectId)&&(where.architectureId===undefined||row.architectureId===where.architectureId)&&(where.sourceItemType===undefined||row.sourceItemType===where.sourceItemType)&&(where.sourceItemId===undefined||row.sourceItemId===where.sourceItemId)&&(where.targetType===undefined||row.targetType===where.targetType)&&(where.operation===undefined||row.operation===where.operation)&&matchesStatus(row,where))??null,
    findUniqueOrThrow:async({where}:{where:Row})=>{const row=actions.find(value=>value.id===where.id);if(!row)throw new Error('not found');return row;},
    updateMany:async({where,data}:{where:Row;data:Row})=>{const rows=actions.filter(row=>(where.id===undefined||row.id===where.id)&&(where.projectId===undefined||row.projectId===where.projectId)&&(where.resultTargetId===undefined||row.resultTargetId===where.resultTargetId)&&matchesStatus(row,where));rows.forEach(row=>Object.assign(row,data,{updatedAt:now()}));return {count:rows.length};},
  };
  const database={
    storyArchitectureThread:{findFirst:async({where}:{where:Row})=>where.id===currentSource.id&&where.architectureId===currentSource.architectureId&&(where.architecture as Row).projectId==='project-1'?currentSource:null},
    storyArchitectureBeat:{findFirst:async({where}:{where:Row})=>where.id===currentSource.id&&where.architectureId===currentSource.architectureId&&(where.architecture as Row).projectId==='project-1'?currentSource:null},
    storyArchitectureApplyAction:applyDelegate,
    plot:{findMany:async()=>plots.map(({id,order})=>({id,order})),create:async({data}:{data:Row})=>{if(options.failPlot)throw new Error('database detail must not escape');const row={id:`plot-${plots.length+1}`,createdAt:now(),updatedAt:now(),version:1,...data};plots.push(row);return row;}},
    $queryRaw:async()=>[{id:'project-1'}],
    $transaction:async(callback:(transaction:unknown)=>Promise<unknown>)=>{const actionBackup=structuredClone(actions);const plotBackup=structuredClone(plots);try{return await callback(database);}catch(error){actions.splice(0,actions.length,...actionBackup);plots.splice(0,plots.length,...plotBackup);throw error;}},
  };
  return {database:database as unknown as typeof realDb,plots,actions,setSource:(next:Row)=>{currentSource=next;}};
}
const input={projectId:'project-1',architectureId:'architecture-1',sourceItemType:'thread' as const,sourceItemId:'thread-1'};

test('source snapshot and fingerprint are semantic, deterministic and raw-Unicode preserving',()=>{const first=buildArchitectureApplySourceSnapshot('thread',source({title:'か\u3099'}));const second=buildArchitectureApplySourceSnapshot('thread',source({title:'が',updatedAt:new Date('2030-01-01')}));assert.notEqual(fingerprintArchitectureApplySnapshot(first),fingerprintArchitectureApplySnapshot(second));assert.equal(fingerprintArchitectureApplySnapshot(first),fingerprintArchitectureApplySnapshot(buildArchitectureApplySourceSnapshot('thread',source({title:'か\u3099',updatedAt:new Date('2040-01-01')}))));assert.equal(first.status,'approved');assert.equal(first.provenance,'author');assert.equal(first.revision,2);});
test('Thread and Beat mapping are deterministic and never invent unsafe fields',()=>{const thread=buildArchitectureApplySourceSnapshot('thread',source());assert.deepEqual(buildArchitecturePlotPayload('thread',thread,4),{name:'静かな帰路',description:'二人が言葉を交わさず帰る。',plotType:'main',priority:0,status:'planned',tags:[],order:4});const beat=buildArchitectureApplySourceSnapshot('beat',source({title:'決意',summary:'事件への関与を決める',intention:'静かな転換'}));assert.deepEqual(buildArchitecturePlotPayload('beat',beat,1),{name:'決意',description:'事件への関与を決める\n静かな転換',plotType:'main',priority:0,status:'planned',tags:[],order:1});});
test('request DTO rejects every client-controlled authority field and forbidden source type',()=>{assert.deepEqual(parseApplyDraftRequest(input),input);for(const key of ['targetType','operation','payload','status','fingerprint','resultTargetId','sourceSnapshot'])assert.throws(()=>parseApplyDraftRequest({...input,[key]:'forbidden'}),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='forbidden_field');for(const sourceItemType of ['question','constraint','relation'])assert.throws(()=>parseApplyDraftRequest({...input,sourceItemType}),/threadまたはbeat/);assert.throws(()=>parseApplyActionRequest({projectId:'project-1',actionId:'action-1',payload:{}}),/Clientから指定できません/);});
test('approved Thread lifecycle creates no Plot until explicit execute and is idempotent',async()=>{const state=fakeDatabase();const draft=await createStoryArchitectureApplyDraft(input,state.database);assert.equal(draft.status,'draft');assert.equal(state.plots.length,0);const preview=await previewStoryArchitectureApplyAction('project-1',String(draft.id),state.database);assert.equal(state.plots.length,0);assert.deepEqual(preview.impact,{create:1,update:0,delete:0,storyFactMutation:0,knowledgeMutation:0,relationshipMutation:0,chapterMutation:0,foreshadowingMutation:0,storyStateMutation:0,readerRevealMutation:0,canonMutation:0});assert.equal(preview.target.payload.status,'planned');const approved=await approveStoryArchitectureApplyAction('project-1',String(draft.id),state.database);assert.equal(approved.status,'approved');assert.equal(state.plots.length,0);const applied=await executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database);assert.equal(applied.status,'applied');assert.equal(state.plots.length,1);assert.equal(state.plots[0].status,'planned');assert.equal(state.plots[0].plotType,'main');assert.equal(state.plots[0].priority,0);assert.equal(state.plots[0].tags,'[]');assert.equal((await executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database)).resultTargetId,applied.resultTargetId);assert.equal(state.plots.length,1);assert.equal(state.actions[0].sourceItemId,'thread-1');});
test('unapproved/retired source and cross-project source are rejected',async()=>{for(const status of ['proposed','draft','retired']){const state=fakeDatabase(source({status}));await assert.rejects(()=>createStoryArchitectureApplyDraft(input,state.database),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='source_not_approved');}const state=fakeDatabase();await assert.rejects(()=>createStoryArchitectureApplyDraft({...input,projectId:'other'},state.database),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='source_not_found');});
test('source semantic change or retirement after Draft marks approval stale',async()=>{const state=fakeDatabase();const draft=await createStoryArchitectureApplyDraft(input,state.database);state.setSource(source({revision:3,title:'変更後'}));await assert.rejects(()=>approveStoryArchitectureApplyAction('project-1',String(draft.id),state.database),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='source_stale');assert.equal(state.actions[0].status,'stale');assert.equal(state.plots.length,0);});
test('source change between approval and execute becomes stale without Plot',async()=>{const state=fakeDatabase();const draft=await createStoryArchitectureApplyDraft(input,state.database);await approveStoryArchitectureApplyAction('project-1',String(draft.id),state.database);state.setSource(source({revision:3,status:'retired'}));await assert.rejects(()=>executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database));assert.equal(state.actions[0].status,'stale');assert.equal(state.plots.length,0);});
test('cancelled, stale and failed Actions cannot execute',async()=>{const state=fakeDatabase();const draft=await createStoryArchitectureApplyDraft(input,state.database);await cancelStoryArchitectureApplyAction('project-1',String(draft.id),state.database);await assert.rejects(()=>executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database),/approved Apply Action/);for(const status of ['stale','failed']){state.actions[0].status=status;await assert.rejects(()=>executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database),/approved Apply Action/);}assert.equal(state.plots.length,0);});
test('AI source requires completed fresh ProposalRun; author source does not rebuild context',async()=>{const run={id:'run-1',projectId:'project-1',architectureId:'architecture-1',scopeType:'architecture',scopeId:null,request:'設計する',canonMode:'respect_current_canon',contextVersion:'architect-v1',promptVersion:'story-architect-ja-v1',contextFingerprint:'fresh-fingerprint',status:'completed'};const state=fakeDatabase(source({provenance:'ai_proposal',proposalRunId:'run-1',proposalRun:run}));let calls=0;const draft=await createStoryArchitectureApplyDraft(input,state.database,{loadContext:async request=>{calls+=1;assert.equal(request.excludeProposalRunId,'run-1');return {fingerprint:'fresh-fingerprint'} as never;}});assert.equal(draft.status,'draft');assert.equal(calls,1);for(const proposalRun of [null,{...run,status:'failed'}]){const invalid=fakeDatabase(source({provenance:'ai_proposal',proposalRunId:proposalRun?'run-1':null,proposalRun}));await assert.rejects(()=>createStoryArchitectureApplyDraft(input,invalid.database,{loadContext:async()=>({fingerprint:'fresh-fingerprint'} as never)}));}const stale=fakeDatabase(source({provenance:'ai_proposal',proposalRunId:'run-1',proposalRun:run}));await assert.rejects(()=>createStoryArchitectureApplyDraft(input,stale.database,{loadContext:async()=>({fingerprint:'changed'} as never)}),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='proposal_run_stale');const author=fakeDatabase();await createStoryArchitectureApplyDraft(input,author.database,{loadContext:async()=>{throw new Error('author source must not rebuild');}});});
test('Alternative membership is captured but siblings are never read or applied',async()=>{const state=fakeDatabase(source({proposalAlternative:{id:'alternative-db-1',alternativeKey:'alternative_1'}}));const draft=await createStoryArchitectureApplyDraft(input,state.database);assert.equal(draft.status,'draft');assert.equal(state.actions.length,1);assert.equal(state.plots.length,0);});
test('Plot insert failure rolls back mutation and records only safe failed state',async()=>{const state=fakeDatabase(source(),{failPlot:true});const draft=await createStoryArchitectureApplyDraft(input,state.database);await approveStoryArchitectureApplyAction('project-1',String(draft.id),state.database);await assert.rejects(()=>executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='plot_create_failed'&&!error.message.includes('database detail'));assert.equal(state.plots.length,0);assert.equal(state.actions[0].status,'failed');assert.equal(state.actions[0].errorCode,'plot_create_failed');assert.equal(state.actions[0].resultTargetId,null);});
test('successful source cannot produce a second Plot and source remains approved',async()=>{const state=fakeDatabase();const draft=await createStoryArchitectureApplyDraft(input,state.database);await approveStoryArchitectureApplyAction('project-1',String(draft.id),state.database);await executeStoryArchitectureApplyAction('project-1',String(draft.id),state.database);await assert.rejects(()=>createStoryArchitectureApplyDraft(input,state.database),(error:unknown)=>error instanceof StoryArchitectureApplyError&&error.code==='duplicate_apply');assert.equal(state.plots.length,1);assert.equal(source().status,'approved');});
