import {
  STORY_ARCHITECTURE_CONSTRAINT_MODES, STORY_ARCHITECTURE_RELATION_TYPES, STORY_ARCHITECTURE_RHYTHMS,
  STORY_ARCHITECTURE_SCOPES, STORY_ARCHITECTURE_THREAD_TYPES,
  type StoryArchitectureConstraintMode, type StoryArchitectureRelationType, type StoryArchitectureRhythm,
  type StoryArchitectureScope, type StoryArchitectureThreadType,
} from './types';
import { relationHasCycle, STORY_ARCHITECTURE_ACYCLIC_RELATIONS } from './relations';

export const STORY_ARCHITECT_PROMPT_VERSION = 'story-architect-ja-v1' as const;
export const STORY_ARCHITECT_OPERATIONS = ['design_scope','deepen_thread','propose_beats','reorder_beats','propose_alternatives','find_gaps','analyze_impact','propose_questions','answer_question'] as const;
export type StoryArchitectOperation = typeof STORY_ARCHITECT_OPERATIONS[number];
export const STORY_ARCHITECT_OUTPUT_LIMITS = { alternatives:3, threads:12, beats:30, constraints:20, questions:20, relations:50, sources:8, text:4000, rationale:1200, tradeoffs:10 } as const;

export type ProposalRef = { kind:'local'|'existing'; id:string };
export type ProposalSourceRef = { sourceType:string; sourceId:string };
export interface ThreadProposal { localId:string; title:string; description:string; threadType:StoryArchitectureThreadType; customTypeLabel:string|null; sourceRefs:ProposalSourceRef[] }
export interface BeatProposal { localId:string; threadRef:ProposalRef|null; chapterId:string|null; title:string; summary:string; intention:string; storyOrder:number|null; presentationOrder:number|null; rhythm:StoryArchitectureRhythm|null; customRhythmLabel:string|null; sourceRefs:ProposalSourceRef[] }
export interface ConstraintProposal { localId:string; title:string; statement:string; mode:StoryArchitectureConstraintMode; scope:StoryArchitectureScope; threadRef:ProposalRef|null; beatRef:ProposalRef|null; sourceRefs:ProposalSourceRef[] }
export interface QuestionProposal { localId:string; question:string; notes:string; scope:StoryArchitectureScope; threadRef:ProposalRef|null; beatRef:ProposalRef|null; answerToQuestionId:string|null; resolutionCandidate:string|null; sourceRefs:ProposalSourceRef[] }
export interface RelationProposal { localId:string; fromBeatRef:ProposalRef; toBeatRef:ProposalRef; type:StoryArchitectureRelationType; sourceRefs:ProposalSourceRef[] }
export interface StoryArchitectAlternative { localId:string; label:string; rationale:string; tradeoffs:string[]; threads:ThreadProposal[]; beats:BeatProposal[]; constraints:ConstraintProposal[]; questions:QuestionProposal[]; relations:RelationProposal[] }
export interface StoryArchitectOutput { summary:string; alternatives:StoryArchitectAlternative[]; impactNotes:string[]; unresolvedQuestions:string[] }
export interface PresentedArchitectEntities { sourcePairs:ReadonlySet<string>; threadIds:ReadonlySet<string>; beatIds:ReadonlySet<string>; chapterIds:ReadonlySet<string>; questionIds:ReadonlySet<string>; relations:ReadonlyArray<{fromBeatId:string;toBeatId:string;type:StoryArchitectureRelationType}> }

export class StoryArchitectProposalError extends Error { constructor(public readonly code:string,public readonly path:string,message:string){super(`${path}: ${message}`);this.name='StoryArchitectProposalError';} }
const fail=(code:string,path:string,message:string):never=>{throw new StoryArchitectProposalError(code,path,message);};
const object=(value:unknown,path:string):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))return fail('invalid_type',path,'objectが必要です。');return value as Record<string,unknown>;};
const keys=(value:Record<string,unknown>,allowed:readonly string[],path:string)=>{const key=Object.keys(value).find(candidate=>!allowed.includes(candidate));if(key)fail('unknown_key',`${path}.${key}`,'未定義fieldです。');};
const text=(value:unknown,path:string,max:number=STORY_ARCHITECT_OUTPUT_LIMITS.text,empty=false):string=>{if(typeof value!=='string')return fail('invalid_type',path,'文字列が必要です。');const candidate=value as string;if(!empty&&!candidate.trim())fail('invalid_type',path,'文字列が必要です。');if(candidate.length>max)fail('output_bound_exceeded',path,`最大${max}文字です。`);return candidate;};
function array(value:unknown,path:string,max:number):unknown[]{if(!Array.isArray(value))return fail('invalid_type',path,'配列が必要です。');const candidate=value as unknown[];if(candidate.length>max)fail('output_bound_exceeded',path,`最大${max}件です。`);return candidate;}
const enumeration=<T extends string>(value:unknown,values:readonly T[],path:string):T=>typeof value==='string'&&values.includes(value as T)?value as T:fail('invalid_value',path,'許可されていない値です。');
const nullableInteger=(value:unknown,path:string)=>value===null?null:Number.isSafeInteger(value)&&(value as number)>=0?value as number:fail('invalid_value',path,'nullまたは0以上の整数が必要です。');
const nullableText=(value:unknown,path:string,max:number=120):string|null=>value===null?null:text(value,path,max);
function sourceRefs(value:unknown,path:string,presented:PresentedArchitectEntities){return array(value,path,STORY_ARCHITECT_OUTPUT_LIMITS.sources).map((raw,index)=>{const item=object(raw,`${path}[${index}]`);keys(item,['sourceType','sourceId'],`${path}[${index}]`);const result={sourceType:text(item.sourceType,`${path}[${index}].sourceType`,100),sourceId:text(item.sourceId,`${path}[${index}].sourceId`,200)};if(!presented.sourcePairs.has(`${result.sourceType}\0${result.sourceId}`))fail('unknown_source',`${path}[${index}]`,'Promptに提示されていないsourceです。');return result;});}
function ref(value:unknown,path:string,kind:'thread'|'beat',locals:Set<string>,presented:PresentedArchitectEntities):ProposalRef|null {if(value===null)return null;const item=object(value,path);keys(item,['kind','id'],path);const refKind=enumeration(item.kind,['local','existing'] as const,`${path}.kind`);const id=text(item.id,`${path}.id`,200);if(refKind==='local'&&!locals.has(id))fail('unknown_local_ref',path,'同じAlternative内にlocal IDがありません。');const existing=kind==='thread'?presented.threadIds:presented.beatIds;if(refKind==='existing'&&!existing.has(id))fail('unknown_entity',path,'Promptに提示されていない既存IDです。');return {kind:refKind,id};}
function unique(values:string[],path:string){const seen=new Set<string>();values.forEach((value,index)=>{if(seen.has(value))fail('duplicate_local_id',`${path}[${index}]`,'local IDが重複しています。');seen.add(value);});}
const localId=(value:unknown,path:string)=>{const result=text(value,path,80);if(!/^[a-z][a-z0-9_]{0,79}$/.test(result))fail('invalid_local_id',path,'local ID形式が不正です。');return result;};

export function validateStoryArchitectOutput(raw:unknown,presented:PresentedArchitectEntities):StoryArchitectOutput {
  const root=object(raw,'$');keys(root,['summary','alternatives','impactNotes','unresolvedQuestions'],'$');
  const summary=text(root.summary,'$.summary',4000,true);
  const rawAlternatives=array(root.alternatives,'$.alternatives',STORY_ARCHITECT_OUTPUT_LIMITS.alternatives);if(rawAlternatives.length===0)fail('invalid_value','$.alternatives','1件以上必要です。');
  const alternatives=rawAlternatives.map((rawAlternative,index)=>{
    const path=`$.alternatives[${index}]`;const item=object(rawAlternative,path);keys(item,['localId','label','rationale','tradeoffs','threads','beats','constraints','questions','relations'],path);
    const alternativeId=localId(item.localId,`${path}.localId`);
    const threadRaw=array(item.threads,`${path}.threads`,STORY_ARCHITECT_OUTPUT_LIMITS.threads);const beatRaw=array(item.beats,`${path}.beats`,STORY_ARCHITECT_OUTPUT_LIMITS.beats);
    const threadIdValues=threadRaw.map((value,i)=>localId(object(value,`${path}.threads[${i}]`).localId,`${path}.threads[${i}].localId`));
    const beatIdValues=beatRaw.map((value,i)=>localId(object(value,`${path}.beats[${i}]`).localId,`${path}.beats[${i}].localId`));
    unique(threadIdValues,`${path}.threads.localId`);unique(beatIdValues,`${path}.beats.localId`);
    const threadIds=new Set<string>(threadIdValues);const beatIds=new Set<string>(beatIdValues);
    const threads=threadRaw.map((value,i)=>{const p=`${path}.threads[${i}]`;const v=object(value,p);keys(v,['localId','title','description','threadType','customTypeLabel','sourceRefs'],p);const threadType=enumeration(v.threadType,STORY_ARCHITECTURE_THREAD_TYPES,`${p}.threadType`);const customTypeLabel=nullableText(v.customTypeLabel,`${p}.customTypeLabel`);if((threadType==='custom')!==Boolean(customTypeLabel))fail('invalid_value',`${p}.customTypeLabel`,'custom時だけlabelが必要です。');return {localId:localId(v.localId,`${p}.localId`),title:text(v.title,`${p}.title`,200),description:text(v.description,`${p}.description`,4000,true),threadType,customTypeLabel,sourceRefs:sourceRefs(v.sourceRefs,p+'.sourceRefs',presented)};});
    const beats=beatRaw.map((value,i)=>{const p=`${path}.beats[${i}]`;const v=object(value,p);keys(v,['localId','threadRef','chapterId','title','summary','intention','storyOrder','presentationOrder','rhythm','customRhythmLabel','sourceRefs'],p);const chapterId=v.chapterId===null?null:text(v.chapterId,`${p}.chapterId`,200);if(chapterId&&!presented.chapterIds.has(chapterId))fail('unknown_entity',`${p}.chapterId`,'Promptに提示されていないChapterです。');const rhythm=v.rhythm===null?null:enumeration(v.rhythm,STORY_ARCHITECTURE_RHYTHMS,`${p}.rhythm`);const customRhythmLabel=nullableText(v.customRhythmLabel,`${p}.customRhythmLabel`);if((rhythm==='custom')!==Boolean(customRhythmLabel))fail('invalid_value',`${p}.customRhythmLabel`,'custom時だけlabelが必要です。');return {localId:localId(v.localId,`${p}.localId`),threadRef:ref(v.threadRef,p+'.threadRef','thread',threadIds,presented),chapterId,title:text(v.title,p+'.title',200),summary:text(v.summary,p+'.summary',4000,true),intention:text(v.intention,p+'.intention',4000,true),storyOrder:nullableInteger(v.storyOrder,p+'.storyOrder'),presentationOrder:nullableInteger(v.presentationOrder,p+'.presentationOrder'),rhythm,customRhythmLabel,sourceRefs:sourceRefs(v.sourceRefs,p+'.sourceRefs',presented)};});
    const scoped=(value:unknown,i:number,kind:'constraints'|'questions')=>{const p=`${path}.${kind}[${i}]`;const v=object(value,p);const base=kind==='constraints'?['localId','title','statement','mode','scope','threadRef','beatRef','sourceRefs']:['localId','question','notes','scope','threadRef','beatRef','answerToQuestionId','resolutionCandidate','sourceRefs'];keys(v,base,p);const scope=enumeration(v.scope,STORY_ARCHITECTURE_SCOPES,p+'.scope');const threadRef=ref(v.threadRef,p+'.threadRef','thread',threadIds,presented);const beatRef=ref(v.beatRef,p+'.beatRef','beat',beatIds,presented);if(scope==='architecture'&&(threadRef||beatRef)||scope==='thread'&&(!threadRef||beatRef)||scope==='beat'&&(!beatRef||threadRef))fail('invalid_scope',p,'scopeと参照が一致しません。');return {v,p,scope,threadRef,beatRef};};
    const constraints=array(item.constraints,path+'.constraints',STORY_ARCHITECT_OUTPUT_LIMITS.constraints).map((value,i)=>{const {v,p,scope,threadRef,beatRef}=scoped(value,i,'constraints');return {localId:localId(v.localId,p+'.localId'),title:text(v.title,p+'.title',200),statement:text(v.statement,p+'.statement'),mode:enumeration(v.mode,STORY_ARCHITECTURE_CONSTRAINT_MODES,p+'.mode'),scope,threadRef,beatRef,sourceRefs:sourceRefs(v.sourceRefs,p+'.sourceRefs',presented)};});
    const questions=array(item.questions,path+'.questions',STORY_ARCHITECT_OUTPUT_LIMITS.questions).map((value,i)=>{const {v,p,scope,threadRef,beatRef}=scoped(value,i,'questions');const answerToQuestionId=v.answerToQuestionId===null?null:text(v.answerToQuestionId,p+'.answerToQuestionId',200);const resolutionCandidate=nullableText(v.resolutionCandidate,p+'.resolutionCandidate',4000);if(answerToQuestionId&&!presented.questionIds.has(answerToQuestionId))fail('unknown_entity',p+'.answerToQuestionId','Promptに提示されていないQuestionです。');if(Boolean(answerToQuestionId)!==Boolean(resolutionCandidate))fail('invalid_value',p,'回答対象と回答候補は両方指定してください。');return {localId:localId(v.localId,p+'.localId'),question:text(v.question,p+'.question',2000),notes:text(v.notes,p+'.notes',4000,true),scope,threadRef,beatRef,answerToQuestionId,resolutionCandidate,sourceRefs:sourceRefs(v.sourceRefs,p+'.sourceRefs',presented)};});
    const relations=array(item.relations,path+'.relations',STORY_ARCHITECT_OUTPUT_LIMITS.relations).map((value,i)=>{const p=`${path}.relations[${i}]`;const v=object(value,p);keys(v,['localId','fromBeatRef','toBeatRef','type','sourceRefs'],p);const fromBeatRef=ref(v.fromBeatRef,p+'.fromBeatRef','beat',beatIds,presented)!;const toBeatRef=ref(v.toBeatRef,p+'.toBeatRef','beat',beatIds,presented)!;if(fromBeatRef.kind===toBeatRef.kind&&fromBeatRef.id===toBeatRef.id)fail('self_relation',p,'self relationは禁止です。');return {localId:localId(v.localId,p+'.localId'),fromBeatRef,toBeatRef,type:enumeration(v.type,STORY_ARCHITECTURE_RELATION_TYPES,p+'.type'),sourceRefs:sourceRefs(v.sourceRefs,p+'.sourceRefs',presented)};});
    unique([...threads,...beats,...constraints,...questions,...relations].map(value=>value.localId),path+'.localIds');
    const graph=[...presented.relations.map((value,i)=>({id:`existing-${i}`,architectureId:'candidate',fromBeatId:`existing:${value.fromBeatId}`,toBeatId:`existing:${value.toBeatId}`,type:value.type})),...relations.map((value,i)=>({id:String(i),architectureId:'candidate',fromBeatId:`${value.fromBeatRef.kind}:${value.fromBeatRef.id}`,toBeatId:`${value.toBeatRef.kind}:${value.toBeatRef.id}`,type:value.type}))];const relationKeys=graph.map(value=>`${value.fromBeatId}\0${value.toBeatId}\0${value.type}`);unique(relationKeys,path+'.relations');for(const type of STORY_ARCHITECTURE_ACYCLIC_RELATIONS)if(relationHasCycle(graph,type))fail('relation_cycle',path+'.relations',`${type} cycleは禁止です。`);
    return {localId:alternativeId,label:text(item.label,path+'.label',200),rationale:text(item.rationale,path+'.rationale',STORY_ARCHITECT_OUTPUT_LIMITS.rationale,true),tradeoffs:array(item.tradeoffs,path+'.tradeoffs',STORY_ARCHITECT_OUTPUT_LIMITS.tradeoffs).map((v,i)=>text(v,`${path}.tradeoffs[${i}]`,500)),threads,beats,constraints,questions,relations};
  });
  unique(alternatives.map(value=>value.localId),'$.alternatives.localId');
  for(const [key,limit] of Object.entries({threads:STORY_ARCHITECT_OUTPUT_LIMITS.threads,beats:STORY_ARCHITECT_OUTPUT_LIMITS.beats,constraints:STORY_ARCHITECT_OUTPUT_LIMITS.constraints,questions:STORY_ARCHITECT_OUTPUT_LIMITS.questions,relations:STORY_ARCHITECT_OUTPUT_LIMITS.relations}) as Array<[keyof Pick<StoryArchitectAlternative,'threads'|'beats'|'constraints'|'questions'|'relations'>,number]>){const count=alternatives.reduce((sum,value)=>sum+value[key].length,0);if(count>limit)fail('output_bound_exceeded',`$.alternatives.*.${key}`,`Run全体で最大${limit}件です。`);}
  return {summary,alternatives,impactNotes:array(root.impactNotes,'$.impactNotes',20).map((v,i)=>text(v,`$.impactNotes[${i}]`,1000)),unresolvedQuestions:array(root.unresolvedQuestions,'$.unresolvedQuestions',20).map((v,i)=>text(v,`$.unresolvedQuestions[${i}]`,1000))};
}
