import assert from 'node:assert/strict';
import test from 'node:test';
import { validateStoryArchitectOutput, StoryArchitectProposalError, type PresentedArchitectEntities, type StoryArchitectAlternative, type StoryArchitectOutput } from './proposal.js';

const presented:PresentedArchitectEntities={sourcePairs:new Set(['story_fact\0fact-1']),threadIds:new Set(['thread-existing']),beatIds:new Set(['beat-existing-a','beat-existing-b']),chapterIds:new Set(['chapter-1']),questionIds:new Set(['question-1']),relations:[]};
const alternative=():StoryArchitectAlternative=>({localId:'alternative_1',label:'静かな案',rationale:'余韻を守る',tradeoffs:['進行は緩やか'],threads:[],beats:[],constraints:[],questions:[],relations:[]});
const output=():StoryArchitectOutput=>({summary:'提案',alternatives:[alternative()],impactNotes:[],unresolvedQuestions:[]});

test('minimal proposal is valid and raw Unicode is preserved',()=>{const raw=output();raw.summary='  か\u3099👨‍👩‍👧‍👦  ';assert.equal(validateStoryArchitectOutput(raw,presented).summary,raw.summary);});
test('one to three independent alternatives are retained',()=>{const raw=output();raw.alternatives=[alternative(),{...alternative(),localId:'alternative_2',label:'別案'}];assert.equal(validateStoryArchitectOutput(raw,presented).alternatives.length,2);});
test('unknown fields and resolved Question policy are rejected',()=>{assert.throws(()=>validateStoryArchitectOutput({...output(),chainOfThought:'secret'},presented),(error:unknown)=>error instanceof StoryArchitectProposalError&&error.code==='unknown_key');const raw=output() as unknown as Record<string,unknown>;const alternatives=(raw.alternatives as Array<Record<string,unknown>>);alternatives[0].questions=[{localId:'question_1',question:'決めるか',notes:'',scope:'architecture',threadRef:null,beatRef:null,sourceRefs:[],resolution:'確定'}];assert.throws(()=>validateStoryArchitectOutput(raw,presented),/未定義field/);});
test('limits, duplicate local IDs, unknown local refs and unseen IDs are rejected',()=>{const tooMany=output();tooMany.alternatives=Array.from({length:4},(_,i)=>({...alternative(),localId:`alternative_${i}`}));assert.throws(()=>validateStoryArchitectOutput(tooMany,presented),/最大3件/);const duplicate=output();duplicate.alternatives[0].threads=[{localId:'thread_1',title:'A',description:'',threadType:'theme',customTypeLabel:null,sourceRefs:[]},{localId:'thread_1',title:'B',description:'',threadType:'theme',customTypeLabel:null,sourceRefs:[]}];assert.throws(()=>validateStoryArchitectOutput(duplicate,presented),/重複/);const unseen=output();unseen.alternatives[0].beats=[{localId:'beat_1',threadRef:{kind:'existing',id:'prompt-unseen'},chapterId:null,title:'B',summary:'',intention:'',storyOrder:null,presentationOrder:null,rhythm:null,customRhythmLabel:null,sourceRefs:[]}];assert.throws(()=>validateStoryArchitectOutput(unseen,presented),(error:unknown)=>error instanceof StoryArchitectProposalError&&error.code==='unknown_entity');});
test('source boundary, self relation and acyclic relation rules are enforced',()=>{const unseen=output();unseen.alternatives[0].threads=[{localId:'thread_1',title:'A',description:'',threadType:'theme',customTypeLabel:null,sourceRefs:[{sourceType:'story_fact',sourceId:'fact-unseen'}]}];assert.throws(()=>validateStoryArchitectOutput(unseen,presented),(error:unknown)=>error instanceof StoryArchitectProposalError&&error.code==='unknown_source');const self=output();self.alternatives[0].relations=[{localId:'relation_1',fromBeatRef:{kind:'existing',id:'beat-existing-a'},toBeatRef:{kind:'existing',id:'beat-existing-a'},type:'causes',sourceRefs:[]}];assert.throws(()=>validateStoryArchitectOutput(self,presented),/self relation/);const cycle=output();cycle.alternatives[0].relations=[{localId:'relation_1',fromBeatRef:{kind:'existing',id:'beat-existing-a'},toBeatRef:{kind:'existing',id:'beat-existing-b'},type:'precedes',sourceRefs:[]},{localId:'relation_2',fromBeatRef:{kind:'existing',id:'beat-existing-b'},toBeatRef:{kind:'existing',id:'beat-existing-a'},type:'precedes',sourceRefs:[]}];assert.throws(()=>validateStoryArchitectOutput(cycle,presented),/cycle/);for(const type of ['causes','enables'] as const){const allowed=structuredClone(cycle);allowed.alternatives[0].relations.forEach(relation=>{relation.type=type;});assert.equal(validateStoryArchitectOutput(allowed,presented).alternatives[0].relations.length,2);}});
test('local references cannot cross alternatives',()=>{const raw=output();raw.alternatives=[{...alternative(),localId:'alternative_1',beats:[{localId:'beat_a',threadRef:null,chapterId:null,title:'A',summary:'',intention:'',storyOrder:null,presentationOrder:null,rhythm:null,customRhythmLabel:null,sourceRefs:[]}]},{...alternative(),localId:'alternative_2',relations:[{localId:'relation_1',fromBeatRef:{kind:'local',id:'beat_a'},toBeatRef:{kind:'existing',id:'beat-existing-a'},type:'causes',sourceRefs:[]}]}];assert.throws(()=>validateStoryArchitectOutput(raw,presented),(error:unknown)=>error instanceof StoryArchitectProposalError&&error.code==='unknown_local_ref');});
