import assert from 'node:assert/strict';
import test from 'node:test';
import { buildStoryArchitectIdentity, generateStoryArchitectProposal, persistStoryArchitectOutput, presentedArchitectEntities, StoryArchitectRuntimeError } from './runtime.js';
import type { ArchitectContext } from './context.js';
import { db as realDb } from '@/lib/db';

const context={version:'architect-v1',projectId:'project-1',architectureId:'architecture-1',scope:{type:'architecture'},currentInstruction:'設計する',canonMode:'respect_current_canon',canonBoundary:'immutable_boundary',invariants:{proposedIsCanon:false,approvedDesignIsCanon:false,applyAllowed:false,ifOnlyExcluded:true},entries:[],diagnostics:[],omittedEntryIds:[],sourceManifest:[],fingerprint:'fingerprint',serializedLength:100} satisfies ArchitectContext;
const valid=JSON.stringify({summary:'ok',alternatives:[{localId:'alternative_1',label:'案',rationale:'',tradeoffs:[],threads:[],beats:[],constraints:[],questions:[],relations:[]}],impactNotes:[],unresolvedQuestions:[]});
function fakeDatabase(seed:{completed?:unknown;pending?:unknown}={}){const updates:unknown[]=[];let created=0;return {updates,get created(){return created;},storyArchitectureProposalRun:{findFirst:async({where}:{where:{status:string}})=>where.status==='completed'?seed.completed??null:seed.pending??null,updateMany:async(args:unknown)=>{updates.push(args);return {count:1};},create:async()=>{created+=1;return {id:'run-1',projectId:'project-1',architectureId:'architecture-1'};} }};}
type Dependencies=NonNullable<Parameters<typeof generateStoryArchitectProposal>[1]>;
const dependencies=(database:ReturnType<typeof fakeDatabase>,extra:Partial<Dependencies>={}):Dependencies=>({database:database as unknown as typeof realDb,loadContext:async()=>context,complete:async()=>valid,parse:JSON.parse,persist:async(_database,run,output)=>({run,output,status:'completed'}) as never,...extra});
test('identity includes operation and prompt/context versions',()=>{assert.notEqual(buildStoryArchitectIdentity(context,'design_scope'),buildStoryArchitectIdentity(context,'find_gaps'));assert.equal(buildStoryArchitectIdentity(context,'design_scope'),buildStoryArchitectIdentity(context,'design_scope'));});
test('fresh completed run is reused unless force is requested',async()=>{const fresh={id:'fresh'};const reused=await generateStoryArchitectProposal({projectId:'project-1',scope:{type:'architecture'},operation:'design_scope',instruction:'設計する'},dependencies(fakeDatabase({completed:fresh})));assert.equal(reused.outcome,'reused');const database=fakeDatabase({completed:fresh});const forced=await generateStoryArchitectProposal({projectId:'project-1',scope:{type:'architecture'},operation:'design_scope',instruction:'設計する',force:true},dependencies(database));assert.equal(forced.outcome,'completed');assert.equal(database.created,1);});
test('pending is deduplicated and stale recovery runs before acquisition',async()=>{const database=fakeDatabase({pending:{id:'pending'}});const result=await generateStoryArchitectProposal({projectId:'project-1',scope:{type:'architecture'},operation:'design_scope',instruction:'設計する'},dependencies(database));assert.equal(result.outcome,'pending');assert.equal(database.created,0);assert.equal(database.updates.length,1);});
test('provider and validation failures mark Run failed with safe code',async()=>{for(const extra of [{complete:async()=>{throw new Error('secret provider response');}},{complete:async()=>'{"bad":true}'}]){const database=fakeDatabase();await assert.rejects(()=>generateStoryArchitectProposal({projectId:'project-1',scope:{type:'architecture'},operation:'design_scope',instruction:'設計する'},dependencies(database,extra)),StoryArchitectRuntimeError);assert.equal(database.updates.length,2);assert.doesNotMatch(JSON.stringify(database.updates),/secret provider response/);}});
test('presented boundary is derived only from architect-v1 included entries',()=>{const values=presentedArchitectEntities({...context,entries:[{id:'x',sourceType:'architecture_beat',sourceId:'beat-1',authority:'approved_design',tier:1,required:false,title:'Beat',content:{}},{id:'r',sourceType:'architecture_relation',sourceId:'relation-1',authority:'existing_plan',tier:1,required:false,title:'Relation',content:{fromBeatId:'beat-1',toBeatId:'beat-2',type:'precedes'}}],sourceManifest:[{sourceType:'architecture_beat',sourceId:'beat-1',fingerprint:'x',authority:'approved_design'}]});assert.deepEqual([...values.beatIds],['beat-1']);assert.equal(values.sourcePairs.has('architecture_beat\0beat-1'),true);assert.equal(values.relations.length,1);});
test('atomic persistence keeps every Alternative proposed with ai_proposal provenance',async()=>{const writes:Record<string,unknown[]>={};const many=(name:string)=>async({data}:{data:unknown[]})=>{(writes[name]??=[]).push(...data);return {count:data.length};};const tx={$queryRaw:async()=>[{id:'run-1'}],storyArchitectureProposalAlternative:{create:async({data}:{data:unknown})=>{(writes.alternatives??=[]).push(data);return data;}},storyArchitectureThread:{createMany:many('threads')},storyArchitectureBeat:{createMany:many('beats')},storyArchitectureConstraint:{createMany:many('constraints')},storyArchitectureQuestion:{createMany:many('questions')},storyArchitectureBeatRelation:{createMany:many('relations')},storyArchitectureProposalSource:{createMany:many('sources')},storyArchitectureProposalRun:{findFirst:async()=>({id:'run-1'}),update:async()=>({status:'completed'})}};let transactions=0;const database={$transaction:async(callback:(value:typeof tx)=>Promise<unknown>)=>{transactions+=1;return callback(tx);}} as unknown as typeof realDb;const makeAlternative=(key:string)=>({localId:key,label:key,rationale:'',tradeoffs:[],threads:[{localId:'thread_1',title:'Thread',description:'',threadType:'theme' as const,customTypeLabel:null,sourceRefs:[]}],beats:[],constraints:[],questions:[],relations:[]});await persistStoryArchitectOutput(database,{id:'run-1',projectId:'project-1',architectureId:'architecture-1'},{summary:'',alternatives:[makeAlternative('alternative_1'),makeAlternative('alternative_2')],impactNotes:[],unresolvedQuestions:[]});assert.equal(transactions,1);assert.equal(writes.alternatives.length,2);assert.equal(writes.threads.length,2);for(const row of writes.threads as Array<Record<string,unknown>>){assert.equal(row.status,'proposed');assert.equal(row.provenance,'ai_proposal');assert.equal(row.proposalRunId,'run-1');assert.ok(row.proposalAlternativeId);}assert.equal('storyFact' in tx,false);assert.equal('chapter' in tx,false);});
test('a lazy-recovered Run cannot return late and persist Proposal rows',async()=>{let writes=0;const tx={$queryRaw:async()=>[{id:'run-1'}],storyArchitectureProposalRun:{findFirst:async()=>null},storyArchitectureProposalAlternative:{create:async()=>{writes+=1;}}};const database={$transaction:async(callback:(value:typeof tx)=>Promise<unknown>)=>callback(tx)} as unknown as typeof realDb;await assert.rejects(()=>persistStoryArchitectOutput(database,{id:'run-1',projectId:'project-1',architectureId:'architecture-1'},{summary:'',alternatives:[],impactNotes:[],unresolvedQuestions:[]}),(error:unknown)=>error instanceof StoryArchitectRuntimeError&&error.code==='persistence_failed');assert.equal(writes,0);});
